lecture_3/django_forms/urls.py
from django.urls import path
from . import views

app_name = "django_forms"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("test", views.test, name="test")
]

lecture_3/first_app/urls.py
from django.urls import path
from . import views

app_name = "first_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("javier", views.javier, name="javier"),
    path("<str:name>", views.greet, name="greet")
]

lecture_3/forms/urls.py
from django.urls import path
from . import views

app_name = "forms"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture_3/lecture_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include("first_app.urls")),
    path('styles/', include("styles.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
    path('forms/', include("forms.urls")),
    path('django_forms/', include("django_forms.urls")),
]

lecture_3/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"

urlpatterns = [
    path("", views.index, name="index"),
]

lecture_3/styles/urls.py
from django.urls import path
from . import views

app_name = "styles"
urlpatterns = [
    path("", views.index, name="index")
]

lecture_3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index")
]

lecture_3/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

lecture_3/forms/views.py
from django.shortcuts import render

def index(request):
    return render(request, "forms/index.html")

def add(request):
    return render(request, "forms/add.html")

lecture_3/django_forms/views.py
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

#ws (without sessions)
#ws tasks = ["write a report", "post report to boss", "relaxing"]

#def index(request):
#    return render(request, "django_forms/index.html", {
#        "tasks": tasks
#    })

def index(request):

    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "django_forms/index.html", {
        "tasks": request.session["tasks"]
    })
    
def test(request):
    return render(request, "django_forms/test.html")

def add(request):

    django_form = NewTaskForm(request.POST) # Take in the data the user submitted and save it as form

    if request.method == "POST":
    
        #django_form = NewTaskForm(request.POST) # Take in the data the user submitted and save it as form
        
        if django_form.is_valid():
            task = django_form.cleaned_data["task"] # Isolate the task from the 'cleaned' version of form data
            #ws tasks.append(task) # Add the new task to our list of tasks
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("django_forms:index")) # Redirect user to list of tasks
        
    else: # If the form is invalid, re-render the page with existing information.
        return render(request, "django_forms/add.html", {
            "django_form": django_form
        })
        
    return render(request, "django_forms/add.html", {
        "django_form": NewTaskForm()
    })

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

lecture_3/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

#def index(request):
#     return HttpResponse("<h1 style=\"color:blue\">This is my first Python & Django web app</h1>")

def index(request):
    return render(request, "first_app/index.html")

def javier(request):
    return HttpResponse("Hello, Javier!")

def greet(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

def greet(request, name):
    return render(request, "first_app/greet.html", {
        "name": name.capitalize()
    })

lecture_3/newyear/views.py
from django.shortcuts import render
import datetime

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": True #now.month == 1 and now.day == 1
    })

lecture_3/styles/views.py
from django.shortcuts import render

def index(request):
    return render(request, "styles/index.html")

lecture_3/tasks/views.py
from django.shortcuts import render

tasks = ["foo", "bar", "baz"]

def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

lecture_3/django_forms/templates/django_forms/add.html
{% extends "django_forms/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'django_forms:add' %}" method="post">
		{% csrf_token %}
        {{ django_form }}
        <input type="submit">
    </form>
	<a href="{% url 'django_forms:index' %}">View Tasks</a>
{% endblock %}

lecture_3/django_forms/templates/django_forms/index.html
{% extends "django_forms/layout.html" %}

{% block body %}
    <h1>Task Manager</h1>
	<p>Tasks: {{ Tasks }}</p>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
	<a href="{% url 'django_forms:add' %}">Add a New Task</a>
{% endblock %}

lecture_3/django_forms/templates/django_forms/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
        {% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'django_forms/styles.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

lecture_3/django_forms/templates/django_forms/test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>test</title>
        {% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'django_forms/styles.css' %}">
    </head>
    <body>
        <p>this is a test</p>
    </body>
</html>

lecture_3/newyear/templates/newyear/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year's?</title>
    </head>
    <body>
        {% if newyear %}
            <p>YES, it is Newyear's day!</p>
        {% else %}
            <p>NO, it is <b>NOT</b> Newyear's day</p>
        {% endif %}
    </body>
</html>

lecture_3/styles/templates/styles/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
		<title>Styles using Django</title>
        {% load static %}
		<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    </head>
    <body>
		<h1>Styles using Django</h1>
        <p>This page uses CSS to render style to the site</p>
    </body>
</html>

lecture_3/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% endfor %}
        </ul>
    </body>
</html>